### ISSUE TITLE
DataCleaner don't work on Pentaho 8.3

### ISSUE THREAD

**Issue by rodrigonovo** [datacleaner/DataCleaner#1831]
When trying to profile a Table Input, the following error happens:

Failed to load DataCleaner plugin class: Lorg/apache/metamodel/csv/CsvConfiguration;
java.lang.NoClassDefFoundError: Lorg/apache/metamodel/csv/CsvConfiguration;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at org.datacleaner.util.ReflectionUtils.addFields(ReflectionUtils.java:539)
	at org.datacleaner.util.ReflectionUtils.addFields(ReflectionUtils.java:531)
	at org.datacleaner.util.ReflectionUtils.getAllFields(ReflectionUtils.java:512)
	at org.datacleaner.descriptors.AbstractDescriptor.visitClass(AbstractDescriptor.java:55)
	at org.datacleaner.descriptors.SimpleComponentDescriptor.visitClass(SimpleComponentDescriptor.java:194)
	at org.datacleaner.descriptors.AbstractComponentDescriptor.visitClass(AbstractComponentDescriptor.java:73)
	at org.datacleaner.descriptors.AnnotationBasedAnalyzerComponentDescriptor.<init>(AnnotationBasedAnalyzerComponentDescriptor.java:42)
	at org.datacleaner.descriptors.Descriptors.ofAnalyzer(Descriptors.java:64)
	at org.datacleaner.descriptors.AbstractDescriptorProvider.notFoundAnalyzer(AbstractDescriptorProvider.java:205)
	at org.datacleaner.descriptors.AbstractDescriptorProvider.getAnalyzerDescriptorForClass(AbstractDescriptorProvider.java:88)
	at org.datacleaner.job.builder.AnalysisJobBuilder.addAnalyzer(AnalysisJobBuilder.java:694)
	at org.pentaho.di.profiling.datacleaner.ModelerHelper.createAnalysisJob(ModelerHelper.java:506)
	at org.pentaho.di.profiling.datacleaner.ModelerHelper.profileStep(ModelerHelper.java:406)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:305)
	at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:290)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:157)
	at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:141)
	at org.pentaho.ui.xul.jface.tags.JfaceMenuitem.access$100(JfaceMenuitem.java:43)
	at org.pentaho.ui.xul.jface.tags.JfaceMenuitem$1.run(JfaceMenuitem.java:106)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:545)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:490)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:402)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1384)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7949)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9331)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:710)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
Caused by: java.lang.ClassNotFoundException: org.apache.metamodel.csv.CsvConfiguration
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromParent(KettleURLClassLoader.java:94)
	at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:114)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 44 more

**Comment by kaspersorensen** [comment]
This is more of an issue in the https://github.com/datacleaner/pdi-datacleaner repo
